PROJECT=`my-awesome-frontend-app`
PKG_MANAGER=

setup:
	mkdir -p src/{api,components,context,hooks,pages,services,styles,utils}
	 install
	cp .env.example .env

dev:
	 run dev

build:
	 run build

docker-run:
	docker compose up -d
